Demo working again (#300)
* Bump to Rust 1.76

Closes https://github.com/maplibre/maplibre-rs/issues/298

* Remove unused import `super::noweb::trace::*`

When trying to compile, the following error pops up.

```
error: unused import: `super::noweb::trace::*`
  --> maplibre/src/platform/mod.rs:26:13
   |
26 |     pub use super::noweb::trace::*;
   |             ^^^^^^^^^^^^^^^^^^^^^^
   |
```