Remove unused import `super::noweb::trace::*`
When trying to compile, the following error pops up.

```
error: unused import: `super::noweb::trace::*`
  --> maplibre/src/platform/mod.rs:26:13
   |
26 |     pub use super::noweb::trace::*;
   |             ^^^^^^^^^^^^^^^^^^^^^^
   |
```